// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dst() {
  return window['go']['backend']['App']['Dst']();
}

export function SelectDst() {
  return window['go']['backend']['App']['SelectDst']();
}

export function SelectSrc() {
  return window['go']['backend']['App']['SelectSrc']();
}

export function SetDst(arg1) {
  return window['go']['backend']['App']['SetDst'](arg1);
}

export function SetSrc(arg1) {
  return window['go']['backend']['App']['SetSrc'](arg1);
}

export function Src() {
  return window['go']['backend']['App']['Src']();
}
