// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Dst():Promise<backend.Destination>;

export function SelectDst():Promise<void>;

export function SelectSrc():Promise<void>;

export function SetDst(arg1:backend.Destination):Promise<void>;

export function SetSrc(arg1:backend.Source):Promise<void>;

export function Src():Promise<backend.Source>;
