// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Get():Promise<backend.DataPart>;

export function IsAnswerError():Promise<boolean|string>;

export function IsAnswerReady():Promise<boolean>;

export function IsOfferError():Promise<boolean|string>;

export function IsOfferReady():Promise<boolean>;

export function Set(arg1:backend.DataPart):Promise<void>;
