// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Get():Promise<backend.DataPart>;

export function Set(arg1:backend.DataPart):Promise<void>;
