// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['backend']['Data']['Get']();
}

export function IsAnswerError() {
  return window['go']['backend']['Data']['IsAnswerError']();
}

export function IsAnswerReady() {
  return window['go']['backend']['Data']['IsAnswerReady']();
}

export function IsOfferError() {
  return window['go']['backend']['Data']['IsOfferError']();
}

export function IsOfferReady() {
  return window['go']['backend']['Data']['IsOfferReady']();
}

export function Set(arg1) {
  return window['go']['backend']['Data']['Set'](arg1);
}
