// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['backend']['Data']['Get']();
}

export function Set(arg1) {
  return window['go']['backend']['Data']['Set'](arg1);
}
