// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Get():Promise<backend.OfferData>;

export function Set(arg1:backend.OfferData):Promise<void>;
